### ISSUE TITLE
Z-order for user menu

### ISSUE THREAD

**Issue by systemcrash** [happyDomain/happydomain#11]
![usermenu](https://user-images.githubusercontent.com/647633/221637921-ae9de3e7-5981-4026-91b8-9ff2663447ed.png)

needs tweaking...

**Comment by nemunaire** [comment]
Fixed in c8ac369bc28d16d97b457f16a6389efd193e4159

The issue was due to non-parents items (I discover the rule): dropdown had a z-index of 1000, list-item was 2. Now the header has a z-index of 100 (which is greater than the list-item's z-index)

**Comment by systemcrash** [comment]
Confirmed
