### ISSUE TITLE
initial history entries

### ISSUE THREAD

**Issue by systemcrash** [happyDomain/happydomain#13]
When first adding a domain, there are two entries:

![history](https://user-images.githubusercontent.com/647633/221644655-5f735944-3560-4a3c-9d49-7badd333c3a0.png)

But clicking on them shows no immediate discernible difference. 

Is this expected? If so, I think these should be documented and what a user should expect from each of them.

**Comment by systemcrash** [comment]
OK, I *think* I get it. The lowest chronological entry seems to be the 'initial' entry, as it was at NXDOMAIN. And the next is the current 'working copy'?

**Comment by nemunaire** [comment]
Exact. This is the WIP zone. The first item is here to be able to revert changes.

There is a topic on our side to have a better history page. And a better history management, eventually with branches...
