### ISSUE TITLE
TTL in "See corresponding records" is wrong

### ISSUE THREAD

**Issue by mathieumd** [happyDomain/happydomain#25]
An `A` RR created from happyDomain is showing:

> test A 1.2.3.4
> 
> Class    IN 
> TTL    3600 
> RRType    A (0x1)
> A    1.2.3.4

However, it's actual TTL after being created into PowerDNS, is 86400:
> test.example.com   86400   IN      A       1.2.3.4

PS: BTW, the `<div>` shown when clicking the button "See corresponding records" should not have a `max-height: 120px;"`, IMHO!
![Should not max-height=120px](https://github.com/happyDomain/happydomain/assets/2104679/beb691fa-5b0d-452e-95b1-6b94ddc82659)

PPS: (Sorry!) When trying to increase the TTL value from 0 to, by example, 7200, I get an error popup:
> Something is wrong in received data: json: cannot unmarshal string into Go struct field ServiceMeta._ttl of type uint32

**Comment by nemunaire** [comment]
I ack the whole issue. Thanks for your review!

What behavior did you expect instead of `max-height: 120px;`?

**Comment by mathieumd** [comment]
> What behavior did you expect instead of `max-height: 120px;`?

Simply removing it makes contents visible, while leaving it displays scrollbars both at right and bottom, which crops the contents.

But if you need to set a max-height, maybe it'll be better to use `em` instead of `px`?

**Comment by nemunaire** [comment]
As a Service, in the meaning of happyDomain, could regroup many records, we need to cap the maximum size to something that keep the modal usable. I don't know if the expanded/explained mode is really useful, perhaps it should be better to include the TTL in the raw line, when it's not the default zone TTL (as we could expect in a zone file).

Regarding the size, this region is now resizable, keeping the default to 120px.
