### ISSUE TITLE
Add OpenID authentication and RBAC features

### ISSUE THREAD

**Issue by WhatANiceChick** [happyDomain/happydomain#27]
It will be great to have the ability to authenticate users through OpenID.

Moreover, RBAC features would be appreciated. Now, any authenticated users can change configuration, add/delete any of the DNS entries, etc.
At least, I think an 'admin' role feature should be added. This allows for example only few members to add DNS providers or see/change provider configuration (that contains secrets).

**Comment by nemunaire** [comment]
Hi @WhatANiceChick!

OpenID authentication has been implemented, the commit will land today in the main branch.

RBAC features is on the roadmap, I'll close the this issue in favor of [this feedack](https://feedback.happydomain.org/posts/1/share-the-zone-edition-with-others-users).

**Comment by nemunaire** [comment]
> I wanted to check your feedback link and I'm getting a SSL/TLS error.

Indeed, the router misbehaves with IPv4 connections. This is fixed now.

**Comment by WhatANiceChick** [comment]
It's fixed, thanks.

OpenID have been tested and worked nicely, great job !
