### ISSUE TITLE
Change history author missing in History of change

### ISSUE THREAD

**Issue by WhatANiceChick** [happyDomain/happydomain#29]
When going into the 'History of change' of a domain (of a DynamicDNS provider in my case), I've in fact the history of addition and deletion with the time and date but not the user who committed the change.

**Comment by nemunaire** [comment]
I added the email of the author:
![image](https://github.com/happyDomain/happydomain/assets/682394/a2cef2fd-1e62-46ea-befd-a7677ee2bb51)

Note that the avatar at the beginning of the line is one of the author. The alternate text and tooltip also shows the email of the user.
